name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 6" # 09:00hrs SGT

defaults:
  run:
    # NOTE: Default option does not include `-o pipefail` as documented
    # unless explicitly specifying the `bash` shell.
    # https://github.com/actions/runner/issues/353
    shell: bash

jobs:
  build-kicad-full:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    strategy:
      matrix:
        version:
          - "8.0.3"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU static libraries
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Buildx builder
        uses: docker/setup-buildx-action@v3.5.0

      - name: Build container image
        run: |
          docker build \
            --build-arg "KICAD_VERSION=${{ matrix.version }}" \
            --tag "loozhengyuan/kicad:${{ matrix.version }}-full" \
            ./kicad-full

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: loozhengyuan
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push container image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push "loozhengyuan/kicad:${{ matrix.version }}-full"

  build-verdaccio-unsafe:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    strategy:
      matrix:
        version:
          - "5.31.1"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU static libraries
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Buildx builder
        uses: docker/setup-buildx-action@v3.5.0

      - name: Build container image
        run: |
          docker build \
            --build-arg "VERDACCIO_VERSION=${{ matrix.version }}" \
            --tag "loozhengyuan/verdaccio:${{ matrix.version }}-unsafe" \
            ./verdaccio-unsafe

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: loozhengyuan
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push container image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push "loozhengyuan/verdaccio:${{ matrix.version }}-unsafe"
